<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--
    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <style>
      body {
        padding: 60px 0px;
      }
    </style>
    -->
  </head>
  <body>
    <div class="container">
      <h1>Fremont Bridge Bike Traffic</h1>
      <p>Data from <a href="http://data.seattle.gov">data.seattle.gov</a>, plot generated by <a href="http://plot.ly">plot.ly</a>.
      <iframe width={{ w }} height={{ h }} seamless="seamless" src={{ ploturl }}></iframe>
    </div>
    <!--
    <script src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  -->
  </body>
</html>
